export default {
  API_URL: process.env.REACT_APP_API_URL,
  DEFAULT_MEETING_PWD:process.env.REACT_APP_DEFAULT_MEETING_PWD,
  PEER_SERVER:process.env.REACT_APP_PEER_SERVER,
  SOCKET_URL:process.env.REACT_APP_SOCKET_IO_URL,
  SOCKET_PORT:process.env.REACT_APP_SOCKET_IO_PORT,  
}